# Generated by Django 3.1.1 on 2020-09-15 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whishlist', '0002_auto_20200915_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='whishlist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='whishlist.wishlist'),
        ),
    ]
