# Generated by Django 3.1.1 on 2020-09-17 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('whishlist', '0004_reservedcontenttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='author_id',
            new_name='author',
        ),
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
