# Generated by Django 3.1.1 on 2020-09-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whishlist', '0006_auto_20200917_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='author',
        ),
    ]
